spring.application.name=backend

bcentral.user=${BCENTRAL_USER:}
bcentral.pass=${BCENTRAL_PASS:}
bcentral.serie.dolar=F073.TCO.PRE.Z.D

mercadopago.access.token=${MP_ACCESS_TOKEN:}

server.error.include-message=always